// src/lib/Menu.svelte
<script lang="ts">
  import { slide } from 'svelte/transition';
  
  export let onNewGame: () => void;
  export let onShare: () => void;
  export let onToggleTheme: () => void;
  export let isDarkMode: boolean;
  
  let showMenu = false;
  let showHelp = false;
  let showPrivacy = false;
  let showContact = false;
</script>

<div class="title-bar">
  <h1>Shape Sorter</h1>
  <div class="controls">
    <button 
      class="theme-toggle" 
      on:click={onToggleTheme}
      aria-label={isDarkMode ? 'Switch to light mode' : 'Switch to dark mode'}
    >
      {isDarkMode ? '☀️' : '🌙'}
    </button>
    <button 
      class="burger" 
      on:click={() => showMenu = !showMenu}
      aria-label="Open menu"
      aria-expanded={showMenu}
      aria-controls="menu"
    >
      <div class="burger-line" />
      <div class="burger-line" />
      <div class="burger-line" />
    </button>
  </div>
</div>

{#if showMenu}
  <div 
    id="menu"
    class="menu" 
    transition:slide
    role="menu"
  >
    <button 
      on:click={() => { onNewGame(); showMenu = false; }}
      role="menuitem"
    >
      New Game
    </button>
    <button 
      on:click={() => { onShare(); showMenu = false; }}
      role="menuitem"
    >
      Share Game
    </button>
    <button 
      on:click={() => { showHelp = true; showMenu = false; }}
      role="menuitem"
    >
      How to Play
    </button>
    <button 
      on:click={() => { showPrivacy = true; showMenu = false; }}
      role="menuitem"
    >
      Privacy
    </button>
    <button 
      on:click={() => { showContact = true; showMenu = false; }}
      role="menuitem"
    >
      Contact
    </button>
  </div>
{/if}

{#if showHelp || showPrivacy || showContact}
  <div 
    class="modal"
    role="dialog"
    aria-modal="true"
  >
    <div class="modal-content">
      {#if showHelp}
        <h2>How to Play</h2>
        <p>1. Drag and drop shapes onto the 6x6 grid</p>
        <p>2. Complete rows or columns to clear them and score points</p>
        <p>3. Game ends when no more shapes can be placed</p>
        <button on:click={() => showHelp = false}>Close</button>
      {/if}
      {#if showPrivacy}
        <h2>Privacy Policy</h2>
        <p>We don't collect any personal data. Game seeds are stored in the URL only.</p>
        <button on:click={() => showPrivacy = false}>Close</button>
      {/if}
      {#if showContact}
        <h2>Contact Us</h2>
        <p>Email: example@shapesort.game</p>
        <button on:click={() => showContact = false}>Close</button>
      {/if}
    </div>
  </div>
{/if}

<style>
  .title-bar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 20px;
    background: var(--title-bg);
    color: var(--title-text);
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 100;
  }

  .controls {
    display: flex;
    gap: 12px;
    align-items: center;
  }

  h1 {
    margin: 0;
    font-size: 1.5rem;
  }

  .burger {
    background: none;
    border: none;
    padding: 10px;
    cursor: pointer;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }

  .burger-line {
    width: 24px;
    height: 2px;
    background: var(--title-text);
    transition: all 0.3s ease;
  }

  .theme-toggle {
    background: none;
    border: none;
    font-size: 1.5rem;
    cursor: pointer;
    padding: 4px;
  }

  .menu {
    position: fixed;
    top: 60px;
    right: 0;
    background: var(--menu-bg);
    box-shadow: var(--menu-shadow);
    z-index: 90;
    display: flex;
    flex-direction: column;
    padding: 10px;
    border-radius: 0 0 0 8px;
  }

  .menu button {
    background: none;
    border: none;
    padding: 10px 20px;
    text-align: left;
    cursor: pointer;
    white-space: nowrap;
    color: var(--text-color);
  }

  .menu button:hover {
    background: var(--menu-hover);
  }

  .modal {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: var(--modal-overlay);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 110;
  }

  .modal-content {
    background: var(--modal-bg);
    color: var(--text-color);
    padding: 20px;
    border-radius: 8px;
    max-width: 500px;
    margin: 20px;
  }
</style>

// src/components/Menu.tsx
import { useState } from 'react';

type MenuProps = {
  onNewGame: () => void;
  onShare: () => void;
  onToggleTheme: () => void;
  onToggleFullscreen: () => void;
  isDarkMode: boolean;
  isFullscreen: boolean;
};

export function Menu({ 
  onNewGame, 
  onShare, 
  onToggleTheme, 
  onToggleFullscreen,
  isDarkMode,
  isFullscreen 
}: MenuProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [modalContent, setModalContent] = useState<'help' | 'privacy' | 'contact' | 'scoring' | null>(null);

  const handleMenuClick = (action: () => void) => {
    action();
    setIsOpen(false);
  };

  const handleModalClose = () => {
    setModalContent(null);
  };

  return (
    <>
      <div className="fixed top-0 left-0 right-0 z-50 flex justify-between items-center px-5 py-3 bg-[var(--title-bg)] text-[var(--title-text)]">
        <h1 className="text-xl font-bold m-0">Shape Sorter</h1>
        <div className="flex gap-3 items-center">
          <button
            onClick={onToggleTheme}
            className="bg-transparent border-none text-2xl cursor-pointer p-1"
            aria-label={isDarkMode ? 'Switch to light mode' : 'Switch to dark mode'}
          >
            {isDarkMode ? '☀️' : '🌙'}
          </button>
          <button
            onClick={onToggleFullscreen}
            className="bg-transparent border-none text-2xl cursor-pointer p-1"
            aria-label={isFullscreen ? 'Exit fullscreen' : 'Enter fullscreen'}
          >
            {isFullscreen ? '⊕' : '⤢'}
          </button>
          <button
            onClick={() => setIsOpen(!isOpen)}
            className="flex flex-col gap-1 bg-transparent border-none p-2 cursor-pointer"
            aria-label="Open menu"
            aria-expanded={isOpen}
          >
            <div className="w-6 h-0.5 bg-[var(--title-text)]" />
            <div className="w-6 h-0.5 bg-[var(--title-text)]" />
            <div className="w-6 h-0.5 bg-[var(--title-text)]" />
          </button>
        </div>
      </div>

      {isOpen && (
        <div className="fixed top-[60px] right-0 z-40 bg-[var(--menu-bg)] shadow-lg rounded-bl-lg overflow-hidden">
          <div className="flex flex-col">
            <button
              onClick={() => handleMenuClick(onNewGame)}
              className="px-5 py-3 text-left hover:bg-[var(--menu-hover)] text-[var(--text-color)]"
            >
              New Game
            </button>
            <button
              onClick={() => handleMenuClick(onShare)}
              className="px-5 py-3 text-left hover:bg-[var(--menu-hover)] text-[var(--text-color)]"
            >
              Share Game
            </button>
            <button
              onClick={() => {
                setModalContent('scoring');
                setIsOpen(false);
              }}
              className="px-5 py-3 text-left hover:bg-[var(--menu-hover)] text-[var(--text-color)]"
            >
              Scoring
            </button>
            <button
              onClick={() => {
                setModalContent('help');
                setIsOpen(false);
              }}
              className="px-5 py-3 text-left hover:bg-[var(--menu-hover)] text-[var(--text-color)]"
            >
              How to Play
            </button>
            <button
              onClick={() => {
                setModalContent('privacy');
                setIsOpen(false);
              }}
              className="px-5 py-3 text-left hover:bg-[var(--menu-hover)] text-[var(--text-color)]"
            >
              Privacy
            </button>
            <button
              onClick={() => {
                setModalContent('contact');
                setIsOpen(false);
              }}
              className="px-5 py-3 text-left hover:bg-[var(--menu-hover)] text-[var(--text-color)]"
            >
              Contact
            </button>
          </div>
        </div>
      )}

      {modalContent && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-[var(--modal-overlay)]">
          <div className="bg-[var(--modal-bg)] p-6 rounded-lg max-w-md mx-4">
            {modalContent === 'help' && (
              <>
                <h2 className="text-xl font-bold mb-4">How to Play</h2>
                <div className="space-y-2 mb-6">
                  <p>1. Drag and drop shapes onto the 6x6 grid</p>
                  <p>2. Complete rows or columns to clear them and score points</p>
                  <p>3. Game ends when no more shapes can be placed</p>
                </div>
              </>
            )}
            {modalContent === 'scoring' && (
              <>
                <h2 className="text-xl font-bold mb-4">Scoring System</h2>
                <div className="space-y-3 mb-6">
                  <p><strong>Basic Points:</strong></p>
                  <ul className="list-disc pl-5 space-y-1">
                    <li>100 points for each completed row or column</li>
                    <li>500 bonus points for clearing the entire grid</li>
                  </ul>
                  
                  <p><strong>Special Shapes:</strong></p>
                  <ul className="list-disc pl-5 space-y-1">
                    <li>At 1000 points: Unlock diagonal down shape (↘)</li>
                    <li>At 2000 points: Unlock diagonal up shape (↗)</li>
                  </ul>
                  
                  <p className="text-sm opacity-80 mt-4">
                    Tip: Try to clear multiple lines at once and aim for grid clears to maximize your score!
                  </p>
                </div>
              </>
            )}
            {modalContent === 'privacy' && (
              <>
                <h2 className="text-xl font-bold mb-4">Privacy Policy</h2>
                <p className="mb-6">We don't collect any personal data. Game seeds are stored in the URL only.</p>
              </>
            )}
            {modalContent === 'contact' && (
              <>
                <h2 className="text-xl font-bold mb-4">Contact Us</h2>
                <p className="mb-6">Email: example@shapesort.game</p>
              </>
            )}
            <button
              onClick={handleModalClose}
              className="w-full px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
            >
              Close
            </button>
          </div>
        </div>
      )}
    </>
  );
}
