// src/App.tsx
import { useState, useEffect } from 'react';
import { GameGrid } from './components/GameGrid';
import { CurrentShape } from './components/CurrentShape';
import { Menu } from './components/Menu';
import { SplashScreen } from './components/SplashScreen';
import { GameLayout } from './components/GameLayout';
import { GameState } from './lib/GameState';
import { toggleFullscreen, isFullscreen } from './lib/utils/fullscreen';

export default function App() {
  const [gameState] = useState(() => new GameState(
    new URLSearchParams(window.location.search).get('seed') || undefined
  ));
  const [score, setScore] = useState(gameState.score);
  const [grid, setGrid] = useState(gameState.grid);
  const [currentShape, setCurrentShape] = useState(gameState.currentShape);
  const [nextShape, setNextShape] = useState(gameState.nextShape);
  const [gameOver, setGameOver] = useState(gameState.gameOver);
  const [lastShape, setLastShape] = useState(gameState.lastShape);
  const [isDarkMode, setIsDarkMode] = useState(
    window.matchMedia('(prefers-color-scheme: dark)').matches
  );
  const [isFullscreenMode, setIsFullscreenMode] = useState(isFullscreen());
  const [showSplash, setShowSplash] = useState(() => {
    return localStorage.getItem('shapeSorterSplashDismissed') !== 'true';
  });
  const [key, setKey] = useState(0);

  useEffect(() => {
    window.history.replaceState({}, '', `?seed=${gameState.seed}`);
    if (isDarkMode) {
      document.documentElement.classList.add('dark');
    }

    const handleFullscreenChange = () => {
      setIsFullscreenMode(isFullscreen());
    };

    document.addEventListener('fullscreenchange', handleFullscreenChange);
    return () => {
      document.removeEventListener('fullscreenchange', handleFullscreenChange);
    };
  }, []);

  const handleShapePlacement = async (x: number, y: number) => {
    if (!gameState.placeShape(x, y)) return;
    
    await new Promise(resolve => setTimeout(resolve, 400));
    
    const linesToClear = gameState.findLinesToClear();
    if (linesToClear.length > 0) {
      await new Promise(resolve => setTimeout(resolve, 800));
      gameState.clearLines(linesToClear);
    }
    
    gameState.nextTurn();
    
    setScore(gameState.score);
    setGrid([...gameState.grid]);
    setCurrentShape(gameState.currentShape);
    setNextShape(gameState.nextShape);
    setGameOver(gameState.gameOver);
    setLastShape(gameState.lastShape);
    setKey(prev => prev + 1);
  };

  const handleNewGame = () => {
    const newGameState = new GameState();
    window.history.replaceState({}, '', `?seed=${newGameState.seed}`);
    
    setScore(newGameState.score);
    setGrid([...newGameState.grid]);
    setCurrentShape(newGameState.currentShape);
    setNextShape(newGameState.nextShape);
    setGameOver(newGameState.gameOver);
    setLastShape(newGameState.lastShape);
    
    Object.assign(gameState, newGameState);
  };

  const handleShare = () => {
    const url = `${window.location.origin}${window.location.pathname}?seed=${gameState.seed}`;
    navigator.clipboard.writeText(url);
    alert('Game URL copied to clipboard!');
  };

  const handleToggleTheme = () => {
    setIsDarkMode(!isDarkMode);
    document.documentElement.classList.toggle('dark');
  };

  const handleToggleFullscreen = () => {
    toggleFullscreen();
  };

  const handleDismissSplash = (dontShowAgain: boolean) => {
    if (dontShowAgain) {
      localStorage.setItem('shapeSorterSplashDismissed', 'true');
    }
    setShowSplash(false);
  };

  return (
    <>
      <Menu 
        onNewGame={handleNewGame}
        onShare={handleShare}
        onToggleTheme={handleToggleTheme}
        onToggleFullscreen={handleToggleFullscreen}
        isDarkMode={isDarkMode}
        isFullscreen={isFullscreenMode}
      />

      {showSplash && (
        <SplashScreen onDismiss={handleDismissSplash} />
      )}

      <main className="pt-16 min-h-screen">
        {!gameOver ? (
          <GameLayout
            score={score}
            grid={
              <GameGrid
                grid={grid}
                currentShape={currentShape}
                onCellDrop={handleShapePlacement}
                isFullscreen={isFullscreenMode}
              />
            }
            current={
              <CurrentShape
                shape={currentShape}
                isDraggable={true}
              />
            }
            next={
              <CurrentShape
                shape={nextShape}
                isDraggable={false}
              />
            }
          />
        ) : (
          <div className="game-over bg-[var(--modal-bg)] p-5 rounded-lg text-center max-w-md mx-auto mt-8">
            <h2 className="text-xl font-bold mb-3">Game Over!</h2>
            <p className="mb-3">Final Score: {score}</p>
            {lastShape && (
              <div className="last-shape mb-5 p-3 bg-red-500/10 rounded">
                <p className="mb-2">This shape couldn't be placed:</p>
                <CurrentShape shape={lastShape} isDraggable={false} />
              </div>
            )}
            <button
              onClick={handleNewGame}
              className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
            >
              Play Again
            </button>
          </div>
        )}
      </main>
    </>
  );
}

// src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import GameGrid from './lib/GameGrid.svelte';
  import CurrentShape from './lib/CurrentShape.svelte';
  import Menu from './lib/Menu.svelte';
  import { GameState } from './lib/GameState';
  import type { Position } from './lib/types';

  let gameState = new GameState(
    new URLSearchParams(window.location.search).get('seed') || undefined
  );
  let gameGridComponent: GameGrid;
  let isDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches;

  async function handleShapePlacement(x: number, y: number) {
    if (!gameState.placeShape(x, y)) return;
    
    const linesToClear = gameState.findLinesToClear();
    if (linesToClear.length > 0) {
      await gameGridComponent.markCellsForClearing(linesToClear);
      gameState.clearLines(linesToClear);
    }
    
    gameState.nextTurn();
    gameState = gameState; // Trigger reactivity
  }

  function handleDragStart(offset: Position) {
    gameGridComponent.setDragOffset(offset);
  }

  function handleNewGame() {
    gameState = new GameState();
    window.history.replaceState({}, '', `?seed=${gameState.seed}`);
  }

  function handleShare() {
    const url = `${window.location.origin}${window.location.pathname}?seed=${gameState.seed}`;
    navigator.clipboard.writeText(url);
    alert('Game URL copied to clipboard!');
  }

  function handleToggleTheme() {
    isDarkMode = !isDarkMode;
    document.documentElement.classList.toggle('dark');
  }

  onMount(() => {
    window.history.replaceState({}, '', `?seed=${gameState.seed}`);
    if (isDarkMode) {
      document.documentElement.classList.add('dark');
    }
  });
</script>

<Menu 
  onNewGame={handleNewGame} 
  onShare={handleShare} 
  onToggleTheme={handleToggleTheme} 
  {isDarkMode} 
/>

<main>
  <div class="game-container">
    <div class="score">Score: {gameState.score}</div>
    
    <div class="game-area">
      <GameGrid 
        bind:this={gameGridComponent}
        grid={gameState.grid} 
        currentShape={gameState.currentShape}
        onCellDrop={handleShapePlacement} 
      />
      
      <div class="side-panel">
        {#if !gameState.gameOver}
          <div class="next-shape">
            <h3>Current Shape:</h3>
            <CurrentShape 
              shape={gameState.currentShape} 
              onDragStart={handleDragStart}
            />
          </div>
        {:else}
          <div class="game-over">
            <h2>Game Over!</h2>
            <p>Final Score: {gameState.score}</p>
            {#if gameState.lastShape}
              <div class="last-shape">
                <p>This shape couldn't be placed:</p>
                <CurrentShape 
                  shape={gameState.lastShape}
                  onDragStart={() => {}}
                />
              </div>
            {/if}
            <button on:click={handleNewGame}>Play Again</button>
          </div>
        {/if}
      </div>
    </div>
  </div>
</main>

<style>
  :global(:root) {
    --text-color: #333;
    --bg-color: #f0f0f0;
    --title-bg: #333;
    --title-text: #fff;
    --menu-bg: #fff;
    --menu-shadow: -2px 2px 5px rgba(0,0,0,0.2);
    --menu-hover: #f0f0f0;
    --modal-overlay: rgba(0, 0, 0, 0.5);
    --modal-bg: #fff;
    --grid-bg: #fff;
    --border-color: #333;
    --cell-border: #999;
    --cell-border-filled: #666;
    --valid-color: #00ff00;
    --invalid-color: #ff0000;
  }

  :global(.dark) {
    --text-color: #fff;
    --bg-color: #1a1a1a;
    --title-bg: #000;
    --title-text: #fff;
    --menu-bg: #333;
    --menu-shadow: -2px 2px 5px rgba(0,0,0,0.4);
    --menu-hover: #444;
    --modal-overlay: rgba(0, 0, 0, 0.7);
    --modal-bg: #333;
    --grid-bg: #2a2a2a;
    --border-color: #666;
    --cell-border: #444;
    --cell-border-filled: #888;
    --valid-color: #00cc00;
    --invalid-color: #cc0000;
  }

  :global(body) {
    background-color: var(--bg-color);
    color: var(--text-color);
  }

  main {
    padding-top: 60px;
    min-height: calc(100vh - 60px);
    display: flex;
    justify-content: center;
    align-items: center;
  }
  
  .game-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 20px;
    max-width: 100%;
    box-sizing: border-box;
  }
  
  .game-area {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 20px;
  }

  @media (min-width: 768px) and (orientation: landscape) {
    .game-area {
      flex-direction: row;
      align-items: flex-start;
      gap: 40px;
    }
  }
  
  .score {
    font-size: 24px;
    font-weight: bold;
    margin-bottom: 20px;
  }
  
  .side-panel {
    min-width: 200px;
  }

  .next-shape {
    padding: 10px;
  }
  
  .game-over {
    padding: 20px;
    background: var(--modal-bg);
    border-radius: 8px;
    text-align: center;
  }

  .last-shape {
    margin: 20px 0;
    padding: 10px;
    background: rgba(255, 0, 0, 0.1);
    border-radius: 4px;
  }

  @media (max-width: 767px) {
    .game-container {
      padding: 10px;
    }
    
    .score {
      font-size: 20px;
      margin-bottom: 10px;
    }
  }
</style>
